### PR TITLE
Fix Arista's ownership of its contributors and contributions

### PR DESCRIPTION
**Pull request by Staphylo**
Currently Arista's contributors are either assigned to Broadcom or considered as individual contributors.
Also all Arista contributions are assigned to Broadcom so make Arista its own entity.

### CODE REVIEW

**Review by lihuay — APPROVED** [review]

**Comment by liushilongbuaa** [comment]
@Staphylo , Please update in sonic-contributor-map repo. That repo has a higher priority.
https://github.com/sonic-net/sonic-contributor-map.

**Comment by liushilongbuaa** [comment]
author.csv is calculated automatically. It will be changed by automation. Send PR to change it don't make sense.

**Comment by liushilongbuaa** [comment]
Changing sii_caculate.py make sense.

**Comment by Staphylo** [comment]
Thanks @liushilongbuaa, I will fix things there. I only just got access to the repo.
I'll close this PR since I see you've made the change in `sii_calculate.py`

**Pull request closed without merging**
