### PR TITLE
Update sonic_ignore, add pptx and pdf

### PR DESCRIPTION
**Pull request by adyeung**
several files in line 56+, line 102+ are presentations from other vendors

### CODE REVIEW

**Comment by adyeung** [comment]
@liushilongbuaa shouldn't all HLD are .md? If that's the case, the script should ignore all except .md and .MD. Also release notes are under separate SII category, need to ignore the release note .md files

**Comment by liushilongbuaa** [comment]
ignore file is not important.
Please update https://github.com/liushilongbuaa/sonctsc/blob/master/sii_hld/sonic_hld.csv directly.
Both release note score and HLD file score are 50. So, I didn't split them.

**Comment by adyeung** [comment]
@liushilongbuaa I assume you will run generate_hld_data.sh again to capture the latest when TSC election happens, instead of updating the result .csv which only serves as a snapshot, won't you want to update the ignore file to correct it?

**Comment by liushilongbuaa** [comment]
> @liushilongbuaa I assume you will run generate_hld_data.sh again to capture the latest when TSC election happens, instead of updating the result .csv which only serves as a snapshot, won't you want to update the ignore file to correct it?

Adding these two lines make sense. But sonic_hdl.csv need change in another PR.
Removing all pdf and pptx files need to be review.

**Pull request merged**
